import { supabase } from '@database/connection/supabase';
import { footerSeoKeywords } from '@/app/constants/seoKeywords';

export default async function sitemap() {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.magnevents.in';

  // Ensure no trailing slashes in static routes to prevent canonical issues
  const staticRoutes = [
    '',
    '/artists',
    '/gallery',
    '/services',
    '/pricing',
    '/how-to-book',
    '/testimonials',
    '/why-choose',
    '/blog-post',
    '/register',
    '/book-singer-for-house-party-in-delhi',
    '/book-live-band-in-delhi',
    '/book-singer-for-wedding',
    '/wedding-band-in-mumbai',
    '/live-band-in-delhi',
    '/corporate-musician-in-bangalore',
    '/wedding-band-in-hyderabad',
    '/house-party-singer-in-ahmedabad',
    '/wedding-singer-in-chennai',
    '/sufi-singer-in-kolkata',
    '/wedding-musicians-in-surat',
    '/wedding-singer-in-pune',
    '/corporate-singer-in-jaipur',
    '/corporate-musician-in-lucknow',
    '/live-singer-in-kanpur',
    '/wedding-singer-in-nagpur',
    '/private-event-singer-in-indore',
    '/house-party-singer-in-thane',
    '/shaadi-singer-in-bhopal',
    '/sufi-singer-in-visakhapatnam',
    '/bollywood-singer-in-pimpri-chinchwad',
    '/birthday-singer-in-patna',
    '/corporate-singer-in-vadodara',
    '/shaadi-singer-in-ghaziabad',
    '/sangeet-singer-in-ludhiana',
    '/corporate-singer-in-agra',
    '/ghazal-singer-in-nashik',
    '/live-band-in-ranchi',
    '/house-party-singer-in-faridabad',
    '/live-singer-in-meerut',
    '/acoustic-singer-in-rajkot',
    '/corporate-event-singer-in-kalyan-dombivli',
    '/acoustic-singer-in-vasai-virar',
    '/live-band-in-varanasi',
    '/corporate-singer-in-srinagar',
    '/bollywood-singer-in-aurangabad',
    '/corporate-event-singer-in-dhanbad',
    '/acoustic-singer-in-amritsar',
    '/punjabi-singer-in-navi-mumbai',
    '/live-singer-in-allahabad',
    '/corporate-musician-in-howrah',
    '/birthday-singer-in-gwalior',
    '/birthday-singer-in-jabalpur',
    '/house-party-singer-in-coimbatore',
    '/live-singer-in-vijayawada',
    '/corporate-musician-in-jodhpur',
    '/corporate-musician-in-madurai',
    '/live-singer-in-raipur',
    '/corporate-musician-in-kota',
    '/corporate-musician-in-chandigarh',
    '/corporate-event-singer-in-guwahati',
    '/ghazal-singer-in-solapur',
    '/corporate-event-singer-in-hubli-dharwad',
    '/live-band-in-mysore',
    '/corporate-musician-in-tiruchirappalli',
    '/live-singer-in-bareilly',
    '/corporate-event-singer-in-aligarh',
    '/live-band-in-tiruppur',
    '/corporate-event-singer-in-gurgaon',
    '/punjabi-singer-in-moradabad',
    '/corporate-singer-in-jalandhar',
    '/ghazal-singer-in-bhubaneswar',
    '/punjabi-singer-in-salem',
    '/wedding-band-in-warangal',
    '/shaadi-singer-in-mira-bhayandar',
    '/bollywood-singer-in-jalgaon',
    '/acoustic-singer-in-guntur',
    '/corporate-singer-in-thiruvananthapuram',
    '/wedding-band-in-bhiwandi',
    '/sufi-singer-in-saharanpur',
    '/live-band-in-gorakhpur',
    '/wedding-musicians-in-bikaner',
    '/shaadi-singer-in-amravati',
    '/corporate-musician-in-noida',
    '/house-party-singer-in-jamshedpur',
    '/live-singer-in-bhilai',
    '/live-music-in-cuttack',
    '/bollywood-singer-in-firozabad',
    '/corporate-event-singer-in-kochi',
    '/shaadi-singer-in-nellore',
    '/sangeet-singer-in-bhavnagar',
    '/sangeet-singer-in-dehradun',
    '/singer-for-events-in-durgapur',
    '/shaadi-singer-in-asansol',
    '/birthday-singer-in-rourkela',
    '/shaadi-singer-in-nanded',
    '/corporate-musician-in-kolhapur',
    '/punjabi-singer-in-ajmer',
    '/wedding-musicians-in-akola',
    '/singer-for-events-in-gulbarga',
    '/live-singer-in-jamnagar',
    '/birthday-singer-in-ujjain',
    '/birthday-singer-in-loni',
    '/bollywood-singer-in-siliguri',
    '/live-band-in-jhansi',
    '/live-singer-in-ulhasnagar',
    '/corporate-musician-in-jammu',
    '/live-music-in-sangli-miraj-kupwad',
    '/wedding-band-in-mangalore',
    '/acoustic-singer-in-erode',
    '/wedding-singer-in-belgaum',
    '/house-party-singer-in-ambattur',
    '/sangeet-singer-in-tirunelveli',
    '/live-band-in-malegaon',
    '/singer-for-events-in-gaya',
    '/wedding-singer-in-udaipur',
    '/live-singer-in-maheshtala',
    '/corporate-singer-in-davanagere',
    '/house-party-singer-in-kozhikode',
    '/wedding-musicians-in-kurnool',
    '/corporate-event-singer-in-rajpur-sonarpur',
    '/wedding-band-in-rajahmundry',
    '/corporate-musician-in-bokaro',
    '/corporate-musician-in-south-dumdum',
    '/wedding-musicians-in-bellary',
    '/bollywood-singer-in-patiala',
    '/corporate-event-singer-in-gopalpur',
    '/sangeet-singer-in-agartala',
    '/corporate-musician-in-bhagalpur',
    '/wedding-band-in-muzaffarnagar',
    '/house-party-singer-in-bhatpara',
    '/shaadi-singer-in-panihati',
    '/live-music-in-latur',
    '/singer-for-events-in-dhule',
    '/punjabi-singer-in-tirupati',
    '/singer-for-events-in-rohtak',
    '/private-event-singer-in-korba',
    '/sangeet-singer-in-bhilwara',
    '/house-party-singer-in-berhampur',
    '/acoustic-singer-in-muzaffarpur',
    '/corporate-event-singer-in-ahmednagar',
    '/punjabi-singer-in-mathura',
    '/private-event-singer-in-kollam',
    '/acoustic-singer-in-avadi',
    '/live-singer-in-kadapa',
    '/wedding-singer-in-kamarhati',
    '/corporate-musician-in-sambalpur',
    '/corporate-musician-in-bilaspur',
    '/bollywood-singer-in-shahjahanpur',
    '/ghazal-singer-in-satara',
    '/wedding-musicians-in-bijapur',
    '/punjabi-singer-in-rampur',
    '/shaadi-singer-in-shivamogga',
    '/house-party-singer-in-chandrapur',
    '/wedding-band-in-junagadh',
    '/private-event-singer-in-thrissur',
    '/acoustic-singer-in-alwar',
    '/shaadi-singer-in-bardhaman',
    '/wedding-band-in-kulti',
    '/corporate-singer-in-kakinada',
    '/live-music-in-nizamabad',
    '/sufi-singer-in-parbhani',
    '/house-party-singer-in-tumkur',
    '/shaadi-singer-in-khammam',
    '/singer-for-events-in-ozhukarai',
    '/corporate-event-singer-in-bihar-sharif',
    '/wedding-singer-in-panipat',
    '/live-band-in-darbhanga',
    '/house-party-singer-in-bally',
    '/live-band-in-aizawl',
    '/wedding-musicians-in-dewas',
    '/singer-for-events-in-ichalkaranji',
    '/corporate-event-singer-in-karnal',
    '/corporate-event-singer-in-bathinda',
    '/corporate-musician-in-jalna',
    '/wedding-singer-in-eluru',
    '/singer-for-events-in-barasat',
    '/wedding-singer-in-kirari-suleman-nagar',
    '/live-band-in-purnia',
    '/birthday-singer-in-satna',
    '/corporate-event-singer-in-mau',
    '/sangeet-singer-in-sonipat',
    '/wedding-singer-in-farrukhabad',
    '/private-event-singer-in-sagar',
    '/corporate-singer-in-durg',
    '/shaadi-singer-in-imphal',
    '/wedding-singer-in-ratlam',
    '/bollywood-singer-in-hapur',
    '/live-band-in-anantapur',
    '/private-event-singer-in-arrah',
    '/live-music-in-karimnagar',
    '/wedding-singer-in-etawah',
    '/private-event-singer-in-ambernath',
    '/singer-for-events-in-north-dumdum',
    '/live-singer-in-bharatpur',
    '/singer-for-events-in-begusarai',
    '/shaadi-singer-in-new-delhi',
    '/corporate-singer-in-gandhidham',
    '/corporate-singer-in-baranagar',
    '/singer-for-events-in-tiruvottiyur',
    '/live-band-in-puducherry',
    '/corporate-event-singer-in-sikar',
    '/house-party-singer-in-thoothukudi',
    '/singer-for-events-in-rewa',
    '/corporate-singer-in-mirzapur',
    '/wedding-singer-in-raichur',
    '/corporate-event-singer-in-pali',
    '/corporate-event-singer-in-ramagundam',
    '/singer-for-events-in-silchar',
    '/corporate-event-singer-in-haridwar',
    '/live-band-in-vijayanagaram',
    '/corporate-event-singer-in-tenali',
    '/house-party-singer-in-nagercoil',
    '/sangeet-singer-in-sri-ganganagar',
    '/sangeet-singer-in-karawal-nagar',
    '/live-music-in-mango',
    '/punjabi-singer-in-thanjavur',
    '/sufi-singer-in-bulandshahr',
    '/corporate-musician-in-uluberia',
    '/ghazal-singer-in-katni',
    '/live-music-in-sambhal',
    '/house-party-singer-in-singrauli',
    '/singer-for-events-in-nadiad',
    '/birthday-singer-in-secunderabad',
    '/live-band-in-naihati',
    '/live-singer-in-yamunanagar',
    '/corporate-singer-in-bidhannagar',
    '/live-band-in-pallavaram',
    '/wedding-band-in-bidar',
    '/sufi-singer-in-munger',
    '/live-singer-in-panchkula',
    '/wedding-musicians-in-burhanpur',
    '/live-music-in-raurkela-industrial-township',
    '/house-party-singer-in-kharagpur',
    '/wedding-singer-in-dindigul',
    '/shaadi-singer-in-gandhinagar',
    '/corporate-singer-in-hospet',
    '/corporate-musician-in-nangloi-jat',
    '/corporate-event-singer-in-malda',
    '/ghazal-singer-in-ongole',
    '/acoustic-singer-in-deoghar',
    '/wedding-band-in-chapra',
    '/live-singer-in-haldia',
    '/bollywood-singer-in-khandwa',
    '/sangeet-singer-in-nandyal',
    '/corporate-event-singer-in-morena',
    '/sangeet-singer-in-amroha',
    '/sangeet-singer-in-anand',
    '/wedding-singer-in-bhind',
    '/wedding-band-in-bhalswa-jahangir-pur',
    '/private-event-singer-in-madhyamgram',
    '/punjabi-singer-in-bhiwani',
    '/live-music-in-berhampore',
    '/house-party-singer-in-ambala',
    '/live-singer-in-morbi',
    '/wedding-singer-in-fatehpur',
    '/wedding-singer-in-raebareli',
    '/corporate-singer-in-khora',
    '/live-band-in-chittoor',
    '/birthday-singer-in-bhusawal'
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date().toISOString(),
    changeFrequency: route === '' ? 'daily' : 'weekly',
    priority: route === '' ? 1.0 : 0.8,
  }));

  let dynamicRoutes = [];
  try {
    const { data: artists } = await supabase
      .from('artists')
      .select('id, name, alias, is_live')
      .eq('is_live', true);

    if (artists) {
      const artistRoutes = artists.map((artist) => {
        const rawName = artist.alias || artist.name || artist.id;
        // Generate a clean SEO slug (e.g., "Neha Kakkar" -> "neha-kakkar")
        const slug = encodeURIComponent(rawName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
        return {
          url: `${baseUrl}/artist/${slug}`,
          lastModified: new Date().toISOString(),
          changeFrequency: 'weekly',
          priority: 0.9,
        };
      });
      dynamicRoutes = [...dynamicRoutes, ...artistRoutes];
    }
    
    // Fetch SEO Cities
    const { data: cities } = await supabase
      .from('seo_cities')
      .select('slug, updated_at')
      .eq('is_active', true);
      
    if (cities) {
      const cityRoutes = cities.map((city) => ({
        url: `${baseUrl}/city/${city.slug}`,
        lastModified: city.updated_at || new Date().toISOString(),
        changeFrequency: 'daily',
        priority: 0.9,
      }));
      dynamicRoutes = [...dynamicRoutes, ...cityRoutes];
    }

    // Fetch SEO Blogs
    const { data: blogs } = await supabase
      .from('seo_blogs')
      .select('slug, updated_at, seo_cities!inner(slug)')
      .eq('status', 'published');

    if (blogs) {
      const blogRoutes = blogs.map((blog) => ({
        url: `${baseUrl}/city/${blog.seo_cities.slug}/blog/${blog.slug}`,
        lastModified: blog.updated_at || new Date().toISOString(),
        changeFrequency: 'weekly',
        priority: 0.8,
      }));
      dynamicRoutes = [...dynamicRoutes, ...blogRoutes];
    }

  } catch (error) {
    console.error('Error fetching dynamic routes for sitemap', error);
  }

  const footerKeywordRoutes = footerSeoKeywords.map((keyword) => {
    const slug = keyword.replace(/ /g, '-');
    return {
      url: `${baseUrl}/${slug}`,
      lastModified: new Date().toISOString(),
      changeFrequency: 'weekly',
      priority: 0.8,
    };
  });

  return [...staticRoutes, ...dynamicRoutes, ...footerKeywordRoutes];
}
