export const footerSeoKeywords = [
  "book a singer for house party in mumbai",
  "book a singer for house party in delhi ncr",
  "live singers in delhi",
  "live singer for house party",
  "singer for house party",
  "guitarist near me",
  "book live singer",
  "sufi singers in delhi",
  "guitarist for house party",
  "live bands for wedding in delhi",
  "singer in delhi",
  "guitarist at home",
  "live singer for house party near me",
  "live singer near me",
  "live bands in delhi",
  "singer for birthday party",
  "live singer",
  "guitarist for birthday party in delhi",
  "live music at home",
  "live music singers near me",
  "singer for home party",
  "live band for wedding",
  "singer near me",
  "singers for wedding",
  "singer at home",
  "singer for house party in gurgaon",
  "local singers near me"
];
